# Generated by Django 3.2.7 on 2021-10-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('Images', models.ImageField(default='', upload_to='blog/images/')),
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
