# Generated by Django 3.2.7 on 2021-10-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='option_one',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='option_one_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='option_two',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='option_two_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Images',
            field=models.ImageField(default='', upload_to='clg/images/'),
        ),
    ]
