# Generated by Django 3.2.7 on 2021-10-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211011_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posts',
            new_name='polls',
        ),
    ]
