# Generated by Django 3.2.7 on 2021-10-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_posts_polls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='polls',
            name='option_one',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='polls',
            name='title',
            field=models.TextField(),
        ),
    ]
