# Generated by Django 3.2.7 on 2021-10-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20211011_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='option_two',
            field=models.CharField(max_length=50),
        ),
    ]
