# Generated by Django 3.2.8 on 2021-10-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_polls_option_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='option_one_count',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='option_two_count',
        ),
        migrations.AddField(
            model_name='polls',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
