# Generated by Django 3.2.8 on 2021-11-10 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0007_likeposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='likes',
            field=models.ManyToManyField(related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='likeposts',
        ),
    ]
