# Generated by Django 3.2.8 on 2021-11-12 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0009_alter_polls_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='likes',
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_like', models.ManyToManyField(default=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
