# Generated by Django 3.2.8 on 2021-11-12 06:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0011_alter_like_post_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='like',
            new_name='likes',
        ),
    ]
