# Generated by Django 3.2.8 on 2021-11-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_rename_like_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='post_id',
        ),
        migrations.AddField(
            model_name='polls',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='likes',
        ),
    ]
