# Generated by Django 3.2.8 on 2021-11-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20211112_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='option_one_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polls',
            name='option_two_count',
            field=models.IntegerField(default=0),
        ),
    ]
